import = ["~/.config/alacritty/themes/themes/atom_one_light.toml"]

[env]
TERM = "xterm-256color"
theme = "light"

[window]
padding.x = 20
padding.y = 20

decorations = "buttonless"
startup_mode = "SimpleFullscreen"
option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 16
offset.x = 0
offset.y = 30
